### PR TITLE
Relaxed versions for pyproject

### PR DESCRIPTION
**Pull request by gabrielfior**
We are using subgrounds for our data fetching on Gnosis. It would be great to have these new dependencies in-place.

### CODE REVIEW

**Review by 0xMochan — APPROVED** [review]

**Comment by 0xMochan** [comment]
Unfortuntely, I messed up the squash some how but I've merged this!

**Comment by gabrielfior** [comment]
@0xMochan  thanks for merging!
I want to integrate these changes with my package (using poetry), but the last released version was 1.8.1 (see https://pypi.org/project/subgrounds/#history). Are you planning to release a new version soon with these changes? Thanks

**Comment by 0xMochan** [comment]
ah, i didn't realize our auto-release flow didn't trigger. I'll look into it!

**Comment by 0xMochan** [comment]
hmm, actually can you explain more why you needed some of the dependencies to be a bit newer. the `^` symbol for versions should allow for newer patch versions if a project depending on `subgrounds` require it, as long as it's specified in a downstream `pyproject.toml`. There's not a specific requirement for subgrounds to be using newer versions in libs like `pydantic`.

**Comment by gabrielfior** [comment]
> hmm, actually can you explain more why you needed some of the dependencies to be a bit newer. the `^` symbol for versions should allow for newer patch versions if a project depending on `subgrounds` require it, as long as it's specified in a downstream `pyproject.toml`. There's not a specific requirement for subgrounds to be using newer versions in libs like `pydantic`.

That was an error from my side. Your reasoning is correct - being more strict on Pydantic does not help. I created a PR (#58 ) to fix this.

> The lack of pypi releases was due to a lack of verification on our emails. Not sure how the CI didn't fail for this as I haven't noticed this but I've resolved it now.

It would be great to have a published package for this new version (1.9.1) soon, as we want to point our poetry dependency to the new release on PyPI (for some reason, publishing a PyPI package which has a dependency of type {git=<GITHUB_REPO>, rev="<BRANCH>"} makes `poetry publish` throw an error.

**Pull request merged**
